spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aureus
    username: aureus
    password: aureus
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080